/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tallerpoo.ventanas;

import TallerPoo.Comorbilidad;
import TallerPoo.*;
import javax.swing.DefaultListModel;

/**
 *
 * @author ACU
 */
public class ifrmSimulacionMovimiento extends javax.swing.JInternalFrame {

    DefaultListModel modelo = new DefaultListModel();
    Persona contagiado = new Persona();

    /**
     * Creates new form ifrmSimulacionMovimiento
     */
    public ifrmSimulacionMovimiento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        movimientoPersona2 = new tallerpoo.ventanas.MovimientoPersona();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setTitle("Escuela");

        javax.swing.GroupLayout movimientoPersona2Layout = new javax.swing.GroupLayout(movimientoPersona2);
        movimientoPersona2.setLayout(movimientoPersona2Layout);
        movimientoPersona2Layout.setHorizontalGroup(
            movimientoPersona2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 479, Short.MAX_VALUE)
        );
        movimientoPersona2Layout.setVerticalGroup(
            movimientoPersona2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 341, Short.MAX_VALUE)
        );

        jButton1.setText("Iniciar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Contagiados");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(movimientoPersona2, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(movimientoPersona2, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Thread[] a = new Thread[TallerPOO.getNinos().size()];
        FiguraPersona[] p = new FiguraPersona[TallerPOO.getNinos().size()];
        for (int i = 0; i < p.length; i++) {
            p[i] = new FiguraPersona(TallerPOO.getNinos().get(i), movimientoPersona2);
            movimientoPersona2.add(p[i]);
        }

        for (int i = 0; i < a.length; i++) {
            a[i] = new Thread(new HiloPersona(p[i]));
        }
        for (int i = 0; i < a.length; i++) {
            a[i].start();

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Persona[] pNinio = new Persona[3];
        FiguraPersona[] p = new FiguraPersona[3];
        Comorbilidad co1 = new Comorbilidad(false, true, true, false, false);
        Comorbilidad co2 = new Comorbilidad(true, false, true, false, false);
        Comorbilidad co3 = new Comorbilidad(false, true, false, true, true);
        TipoCuidado t1 = new TipoCuidado(true, true, true, true);
        TipoCuidado t2 = new TipoCuidado(false, false, true, true);
        TipoCuidado t3 = new TipoCuidado(true, true, false, false);
        Actividad act = new Actividad();
        Hospital h = new Hospital();
        pNinio[0] = new Persona(Edad.NIÑOS, true, false, t2, co1, act, 321, h);
        pNinio[1] = new Persona(Edad.NIÑOS, true, false, t1, co1, act, 321, h);
        pNinio[2] = new Persona(Edad.NIÑOS, true, false, t3, co1, act, 321, h);
        for (int i = 0; i < p.length; i++) {
            p[i] = new FiguraPersona(pNinio[i], movimientoPersona2);
            movimientoPersona2.add(p[i]);
        }
        Thread[] a = new Thread[3];
        for (int i = 0; i < a.length; i++) {
            a[i] = new Thread(new HiloPersona(p[i]));
        }
        for (int i = 0; i < a.length; i++) {
            a[i].start();

        }
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private tallerpoo.ventanas.MovimientoPersona movimientoPersona2;
    // End of variables declaration//GEN-END:variables
}
