/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tallerpoo.ventanas;

import TallerPoo.TallerPOO;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author ACU
 */
public class ifrmSimulacionMayores extends javax.swing.JInternalFrame {

    List<Thread> hilo = new ArrayList();

    /**
     * Creates new form ifrmSimulacionMayores
     */
    public ifrmSimulacionMayores() {
        initComponents();
                FiguraPersona[] p = new FiguraPersona[TallerPOO.getMayores().size()];
        for (int i = 0; i < p.length; i++) {
            p[i] = new FiguraPersona(TallerPOO.getMayores().get(i), movimientoPersona3);
            movimientoPersona3.add(p[i]);
        }

        for (int i = 0; i < p.length; i++) {
            hilo.add(new Thread(new HiloPersona(p[i])));
        }
        for (int i = 0; i < hilo.size(); i++) {
            hilo.get(i).start();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        movimientoPersona3 = new tallerpoo.ventanas.MovimientoPersona();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);
        setTitle("Paseo");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/tallerpoo/imagenes/park.png"))); // NOI18N
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        javax.swing.GroupLayout movimientoPersona3Layout = new javax.swing.GroupLayout(movimientoPersona3);
        movimientoPersona3.setLayout(movimientoPersona3Layout);
        movimientoPersona3Layout.setHorizontalGroup(
            movimientoPersona3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 491, Short.MAX_VALUE)
        );
        movimientoPersona3Layout.setVerticalGroup(
            movimientoPersona3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 353, Short.MAX_VALUE)
        );

        getContentPane().add(movimientoPersona3);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private tallerpoo.ventanas.MovimientoPersona movimientoPersona3;
    // End of variables declaration//GEN-END:variables
}
