/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tallerpoo.ventanas;

import TallerPoo.TallerPOO;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author ACU
 */
public class ifrmSimulacionAdultos extends javax.swing.JInternalFrame {

    List<Thread> hilo = new ArrayList();

    /**
     * Creates new form ifrmSimulacionAdultos
     */
    public ifrmSimulacionAdultos() {
        initComponents();
        FiguraPersona[] p = new FiguraPersona[TallerPOO.getAdultos().size()];
        for (int i = 0; i < p.length; i++) {
            p[i] = new FiguraPersona(TallerPOO.getAdultos().get(i), movimientoPersona1);
            movimientoPersona1.add(p[i]);
        }

        for (int i = 0; i < p.length; i++) {
            hilo.add(new Thread(new HiloPersona(p[i])));
        }
        for (int i = 0; i < hilo.size(); i++) {
            hilo.get(i).start();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        movimientoPersona1 = new tallerpoo.ventanas.MovimientoPersona();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);
        setTitle("Trabajo");
        setToolTipText("");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/tallerpoo/imagenes/bank.png"))); // NOI18N
        setName(""); // NOI18N
        setVisible(false);

        javax.swing.GroupLayout movimientoPersona1Layout = new javax.swing.GroupLayout(movimientoPersona1);
        movimientoPersona1.setLayout(movimientoPersona1Layout);
        movimientoPersona1Layout.setHorizontalGroup(
            movimientoPersona1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        movimientoPersona1Layout.setVerticalGroup(
            movimientoPersona1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(movimientoPersona1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private tallerpoo.ventanas.MovimientoPersona movimientoPersona1;
    // End of variables declaration//GEN-END:variables
}
