/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tallerpoo.ventanas;

import TallerPoo.Comorbilidad;
import TallerPoo.*;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;

/**
 *
 * @author ACU
 */
public class ifrmSimulacionMovimientoNinios extends javax.swing.JInternalFrame {

    List<Thread> hilo = new ArrayList();


    /**
     * Creates new form ifrmSimulacionMovimiento
     */
    public ifrmSimulacionMovimientoNinios() {
        initComponents();
        FiguraPersona[] p = new FiguraPersona[TallerPOO.getNinos().size()];
        for (int i = 0; i < p.length; i++) {
            p[i] = new FiguraPersona(TallerPOO.getNinos().get(i), movimientoPersona2);
            movimientoPersona2.add(p[i]);
        }

        for (int i = 0; i < p.length; i++) {
            hilo.add(new Thread(new HiloPersona(p[i])));
        }
        for (int i = 0; i < hilo.size(); i++) {
            hilo.get(i).start();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        movimientoPersona2 = new tallerpoo.ventanas.MovimientoPersona();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);
        setTitle("Escuela");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/tallerpoo/imagenes/school.png"))); // NOI18N
        setPreferredSize(new java.awt.Dimension(503, 384));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        movimientoPersona2.setLayout(new java.awt.BorderLayout());
        getContentPane().add(movimientoPersona2);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private tallerpoo.ventanas.MovimientoPersona movimientoPersona2;
    // End of variables declaration//GEN-END:variables
}
