/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tallerpoo.ventanas;

import TallerPoo.TallerPOO;

/**
 *
 * @author Joaquin
 */
public class jpanelInformacion extends javax.swing.JPanel implements Runnable {

    /**
     * Creates new form jpanelInformacion
     */
    public jpanelInformacion() {
        initComponents();
        Thread info = new Thread(this);
        info.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPC = new javax.swing.JLabel();
        jPS = new javax.swing.JLabel();
        jPMasCuidan = new javax.swing.JLabel();
        jPSoloTapabocas = new javax.swing.JLabel();
        jPSoloLavanManos = new javax.swing.JLabel();

        jPC.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPC.setText("Personas Contagiadas");
        jPC.setToolTipText("");
        jPC.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPC.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/tallerpoo/imagenes/bed.png"))); // NOI18N
        jPC.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPC.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jPS.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPS.setText("Personas Sanas");
        jPS.setToolTipText("");
        jPS.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPS.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/tallerpoo/imagenes/bed.png"))); // NOI18N
        jPS.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPS.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jPMasCuidan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPMasCuidan.setText("Personas que más se cuidan");
        jPMasCuidan.setToolTipText("");
        jPMasCuidan.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPMasCuidan.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/tallerpoo/imagenes/bed.png"))); // NOI18N
        jPMasCuidan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPMasCuidan.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jPSoloTapabocas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPSoloTapabocas.setText("Personas solo tapabocas");
        jPSoloTapabocas.setToolTipText("");
        jPSoloTapabocas.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPSoloTapabocas.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/tallerpoo/imagenes/bed.png"))); // NOI18N
        jPSoloTapabocas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPSoloTapabocas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jPSoloLavanManos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPSoloLavanManos.setText("Personas que solo se lavan las manos");
        jPSoloLavanManos.setToolTipText("");
        jPSoloLavanManos.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPSoloLavanManos.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/tallerpoo/imagenes/bed.png"))); // NOI18N
        jPSoloLavanManos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPSoloLavanManos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPC)
                    .addComponent(jPS)
                    .addComponent(jPMasCuidan)
                    .addComponent(jPSoloTapabocas)
                    .addComponent(jPSoloLavanManos))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jPC)
                .addGap(18, 18, 18)
                .addComponent(jPS)
                .addGap(18, 18, 18)
                .addComponent(jPMasCuidan)
                .addGap(18, 18, 18)
                .addComponent(jPSoloTapabocas)
                .addGap(18, 18, 18)
                .addComponent(jPSoloLavanManos)
                .addContainerGap(57, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jPC;
    private javax.swing.JLabel jPMasCuidan;
    private javax.swing.JLabel jPS;
    private javax.swing.JLabel jPSoloLavanManos;
    private javax.swing.JLabel jPSoloTapabocas;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        jPC.setText("Personas Contagiadas: " + TallerPOO.getPersona());
    }
}
