/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tallerpoo.ventanas;

import TallerPoo.*;
import java.util.ArrayList;
import java.util.List;

public class PanelSimulacion extends javax.swing.JInternalFrame {

    List<Thread> hiloAdulto = new ArrayList();
    List<Thread> hiloNino = new ArrayList();
    List<Thread> hiloMayor = new ArrayList();

    /**
     * Creates new form PanelSimulacion
     */
    public PanelSimulacion() {
        initComponents();
//        panelAdultos();
//        panelMayores();
        panelNinos();
    }

    /**
     * Panel que muestra la actividad realizada por adultos (trabajo)
     */
    public void panelAdultos() {
        FiguraPersona[] p = new FiguraPersona[TallerPOO.getAdultos().size()];
        for (int i = 0; i < p.length; i++) {
            p[i] = new FiguraPersona(TallerPOO.getAdultos().get(i), jpanelAdultos);
            jpanelAdultos.add(p[i]);
        }

        for (int i = 0; i < p.length; i++) {
            hiloAdulto.add(new Thread(new HiloPersona(p[i])));
        }
        for (int i = 0; i < hiloAdulto.size(); i++) {
            hiloAdulto.get(i).start();
        }
    }

    /**
     * Panel que muestra la actividad realizada por adultos mayores (paseo)
     */
    public void panelMayores() {
        FiguraPersona[] p = new FiguraPersona[TallerPOO.getMayores().size()];
        for (int i = 0; i < p.length; i++) {
            p[i] = new FiguraPersona(TallerPOO.getMayores().get(i), jpanelMayores);
            jpanelMayores.add(p[i]);
        }

        for (int i = 0; i < p.length; i++) {
            hiloMayor.add(new Thread(new HiloPersona(p[i])));
        }
        for (int i = 0; i < hiloMayor.size(); i++) {
            hiloMayor.get(i).start();
        }
    }

    /**
     * Panel que muestra la actividad realizada por los niños (escuela)
     */
    public void panelNinos() {
        FiguraPersona[] p = new FiguraPersona[TallerPOO.getNinos().size()];
        for (int i = 0; i < p.length; i++) {
            p[i] = new FiguraPersona(TallerPOO.getNinos().get(i), jpanelNinos);
            jpanelNinos.add(p[i]);
        }

        for (int i = 0; i < p.length; i++) {
            hiloNino.add(new Thread(new HiloPersona(p[i])));
        }
        for (int i = 0; i < hiloNino.size(); i++) {
            hiloNino.get(i).start();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpanelNinos = new tallerpoo.ventanas.PanelSimulacionGeneral();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jpanelNinos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(jpanelNinos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private tallerpoo.ventanas.PanelSimulacionGeneral jpanelNinos;
    // End of variables declaration//GEN-END:variables
}
