/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tallerpoo.ventanas;

/**
 *
 * @author Joaquin
 */
public class PanelSimulacionGeneral extends javax.swing.JPanel {

    /**
     * Creates new form PanelSimulacionGeneral
     */
    public PanelSimulacionGeneral() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jHospital = new javax.swing.JLabel();
        jEscuela = new javax.swing.JLabel();
        jPaseo = new javax.swing.JLabel();
        jTrabajo = new javax.swing.JLabel();
        jCasa = new javax.swing.JLabel();

        jHospital.setForeground(new java.awt.Color(255, 198, 52));
        jHospital.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tallerpoo/imagenes/hospital.png"))); // NOI18N
        jHospital.setText("Hospital");

        jEscuela.setForeground(new java.awt.Color(255, 198, 52));
        jEscuela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tallerpoo/imagenes/school.png"))); // NOI18N
        jEscuela.setText("Escuela");

        jPaseo.setForeground(new java.awt.Color(255, 198, 52));
        jPaseo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tallerpoo/imagenes/park.png"))); // NOI18N
        jPaseo.setText("Paseo");

        jTrabajo.setForeground(new java.awt.Color(255, 198, 52));
        jTrabajo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tallerpoo/imagenes/bank.png"))); // NOI18N
        jTrabajo.setText("Trabajo");

        jCasa.setForeground(new java.awt.Color(255, 198, 52));
        jCasa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tallerpoo/imagenes/house.png"))); // NOI18N
        jCasa.setText("Casa");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPaseo)
                    .addComponent(jTrabajo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jEscuela)
                    .addComponent(jHospital))
                .addGap(22, 22, 22))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(647, Short.MAX_VALUE)
                .addComponent(jCasa)
                .addGap(268, 268, 268))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jEscuela))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jTrabajo)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 320, Short.MAX_VALUE)
                .addComponent(jCasa)
                .addGap(128, 128, 128)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPaseo)
                    .addComponent(jHospital))
                .addContainerGap())
        );

        getAccessibleContext().setAccessibleName("Simulación General");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jCasa;
    private javax.swing.JLabel jEscuela;
    private javax.swing.JLabel jHospital;
    private javax.swing.JLabel jPaseo;
    private javax.swing.JLabel jTrabajo;
    // End of variables declaration//GEN-END:variables
}
