/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tallerpoo.ventanas;

import TallerPoo.Comorbilidad;
import TallerPoo.Edad;
import TallerPoo.Persona;
import TallerPoo.TallerPOO;
import TallerPoo.TipoCuidado;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author Joaquin
 */
public class PanelMovimiento extends javax.swing.JInternalFrame {

    List<Thread> hiloPersona = new ArrayList();
    List<FiguraPersona> personas = new ArrayList();

    /**
     * Creates new form PanelMovimiento
     */
    public PanelMovimiento() {
        initComponents();
        agregarPersonas();
        jpanelInformacion1= new jpanelInformacion(personas);
    }

    public void agregarPersonas() {
        for (int i = 0; i < TallerPOO.getPersona().size(); i++) {
            personas.add(new FiguraPersona(TallerPOO.getPersona().get(i), panelSimulacionGeneral1));
            panelSimulacionGeneral1.add(personas.get(i));
        }
        for (int i = 0; i <personas.size(); i++) {
            hiloPersona.add(new Thread(new HiloPersona(personas.get(i))));
            
        }
        for (int i = 0; i < personas.size(); i++) {
            hiloPersona.get(i).start();
            
        }
    }



 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelSimulacionGeneral1 = new tallerpoo.ventanas.PanelSimulacionGeneral();
        jpanelHospital1 = new tallerpoo.ventanas.jpanelHospital();
        jpanelInformacion1 = new tallerpoo.ventanas.jpanelInformacion();
        jButton1 = new javax.swing.JButton();

        jButton1.setText("Agregar Contagiados");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelSimulacionGeneral1, javax.swing.GroupLayout.PREFERRED_SIZE, 1012, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jpanelHospital1, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(jpanelInformacion1, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelSimulacionGeneral1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpanelInformacion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jpanelHospital1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Persona[] pAdultos = new Persona[3];
        FiguraPersona[] p = new FiguraPersona[3];
        Comorbilidad co1 = new Comorbilidad(false, true, true, false, false);
        Comorbilidad co2 = new Comorbilidad(true, false, true, false, false);
        Comorbilidad co3 = new Comorbilidad(false, true, false, true, true);
        TipoCuidado t1 = new TipoCuidado(true, true, true, true);
        TipoCuidado t2 = new TipoCuidado(false, false, true, true);
        TipoCuidado t3 = new TipoCuidado(true, true, false, false);
        pAdultos[0] = new Persona(Edad.ADULTOS, true, false, t2, co1, TallerPOO.getActividad(), 321, TallerPOO.getHospital());
        pAdultos[1] = new Persona(Edad.ADULTOS, true, false, t1, co1, TallerPOO.getActividad(), 322, TallerPOO.getHospital());
        pAdultos[2] = new Persona(Edad.ADULTOS, true, false, t3, co1, TallerPOO.getActividad(), 323, TallerPOO.getHospital());
        for (int i = 0; i < p.length; i++) {
            p[i] = new FiguraPersona(pAdultos[i], panelSimulacionGeneral1);
            panelSimulacionGeneral1.add(p[i]);
        }
        Thread[] a = new Thread[3];
        for (int i = 0; i < a.length; i++) {
            a[i] = new Thread(new HiloPersona(p[i]));
        }
        for (int i = 0; i < a.length; i++) {
            a[i].start();
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private tallerpoo.ventanas.jpanelHospital jpanelHospital1;
    private tallerpoo.ventanas.jpanelInformacion jpanelInformacion1;
    private tallerpoo.ventanas.PanelSimulacionGeneral panelSimulacionGeneral1;
    // End of variables declaration//GEN-END:variables
}
