/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tallerpoo.ventanas;

import java.awt.Color;
import java.awt.Graphics;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author Joaquin
 */
public class PanelSimulacionGeneral extends javax.swing.JPanel {

    List<FiguraPersona> p = new ArrayList<>();

    /**
     * Creates new form PanelSimulacionGeneral
     */
    public PanelSimulacionGeneral() {
        initComponents();
    }

    public void add(FiguraPersona per) {
        p.add(per);
    }

    @Override
    public void paintComponent(Graphics g) { // Dibujamos la Persona
        super.paintComponent(g);
        g.setColor(Color.black);
        g.fillRect(0, 0, getWidth(), getHeight());
        for (int i = 0; i < p.size(); i++) {
            p.get(i).paint(g);
        }
        for (int i = 0; i < p.size(); i++) {
            for (int j = 0; j < p.size(); j++) {
                if (collision(p.get(i), p.get(j)) && j != i) {
                    if (!p.get(i).getContagio() && p.get(j).getContagio()) {
                        p.get(i).actividad(p.get(j));
                    } else if (p.get(i).getContagio() && !p.get(j).getContagio()) {
                        p.get(j).actividad(p.get(i));
                    }
                }
            }

        }
    }

    private boolean collision(FiguraPersona a, FiguraPersona b) {
        return a.getBounds().intersects(b.getBounds());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jHospital = new javax.swing.JLabel();
        jPaseo = new javax.swing.JLabel();
        jTrabajo = new javax.swing.JLabel();
        jCasa = new javax.swing.JLabel();
        jEscuela = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(1000, 600));

        jHospital.setForeground(new java.awt.Color(255, 198, 52));
        jHospital.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tallerpoo/imagenes/hospital.png"))); // NOI18N
        jHospital.setText("Hospital");

        jPaseo.setForeground(new java.awt.Color(255, 198, 52));
        jPaseo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tallerpoo/imagenes/park.png"))); // NOI18N
        jPaseo.setText("Paseo");

        jTrabajo.setForeground(new java.awt.Color(255, 198, 52));
        jTrabajo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tallerpoo/imagenes/bank.png"))); // NOI18N
        jTrabajo.setText("Trabajo");

        jCasa.setForeground(new java.awt.Color(255, 198, 52));
        jCasa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tallerpoo/imagenes/house.png"))); // NOI18N
        jCasa.setText("Casa");

        jEscuela.setForeground(new java.awt.Color(255, 198, 52));
        jEscuela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tallerpoo/imagenes/school.png"))); // NOI18N
        jEscuela.setText("Escuela");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jTrabajo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jHospital)
                    .addComponent(jCasa))
                .addGap(22, 22, 22))
            .addGroup(layout.createSequentialGroup()
                .addGap(198, 198, 198)
                .addComponent(jPaseo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(468, Short.MAX_VALUE)
                .addComponent(jEscuela)
                .addGap(433, 433, 433))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTrabajo)
                    .addComponent(jCasa))
                .addGap(205, 205, 205)
                .addComponent(jEscuela)
                .addGap(92, 92, 92)
                .addComponent(jPaseo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addComponent(jHospital)
                .addContainerGap())
        );

        getAccessibleContext().setAccessibleName("Simulación General");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jCasa;
    private javax.swing.JLabel jEscuela;
    private javax.swing.JLabel jHospital;
    private javax.swing.JLabel jPaseo;
    private javax.swing.JLabel jTrabajo;
    // End of variables declaration//GEN-END:variables
}
